name: Docker Image CI

on:
  push:
    branches: ["develop"]

jobs:
  build-and-push-to-docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and tag image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/testedeploy:latest . |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/testedeploy:${{ github.run_number }} .

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/testedeploy:latest | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/testedeploy:${{ github.run_number }}
  modifygit:
    needs: build-and-push-to-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: "uiuqM/DWM-infra-k8s"
          token: ${{ secrets.GIT_PASSWORD }}
      - name: modify the image
        run: |
          git config user.email wilque.coelho@mail.uft.edu.br
          git config user.name uiuqM
          pwd
          cat k8s/api-deploy.yaml
          pwd
          sed -i "s+uiuq/testedeploy.*+uiuq/testedeploy:$RUN_NUMBER+g" k8s/api-deploy.yaml
          cat k8s/api-deploy.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}
